export declare class CountriesSpeakingLanguage {
    constructor();
    getCountry(country_code: string): any;
    getCountryOfficialsLanguages(country_code: string): {
        languages: any;
        languages_codes: any;
    };
    getCountryAllSpeakingLanguages(country_code: string): any;
    hasLanguageAsOfficial(language_code: string, country_code: string): boolean;
    hasLanguage(language_code: string, country_code: string): boolean;
    hasEnglishAsOfficialLanguage(country_code: string): boolean;
    hasMadarinAsOfficialLanguage(country_code: string): boolean;
    hasHindiAsOfficialLanguage(country_code: string): boolean;
    hasSpanishAsOfficialLanguage(country_code: string): boolean;
    hasFrenchAsOfficialLanguage(country_code: string): boolean;
    hasArabicAsOfficialLanguage(country_code: string): boolean;
    hasBengaliAsOfficialLanguage(country_code: string): boolean;
    hasRussianAsOfficialLanguage(country_code: string): boolean;
    hasPortugueseAsOfficialLanguage(country_code: string): boolean;
    hasIndonesianAsOfficialLanguage(country_code: string): boolean;
    hasUrduAsOfficiaAslLanguage(country_code: string): boolean;
    hasJapaneseAsOfficialLanguage(country_code: string): boolean;
    hasGermanAsOfficialLanguage(country_code: string): boolean;
    hasChineseAsOfficialLanguage(country_code: string): boolean;
    hasTurkishAsOfficialLanguage(country_code: string): boolean;
    hasKoreanAsOfficialLanguage(country_code: string): boolean;
    hasYorubaAsOfficialLanguage(country_code: string): boolean;
    hasFonAsOfficialLanguage(country_code: string): boolean;
    hasEnglishAsSpeakingLanguages(country_code: string): boolean;
    hasMadarinAsSpeakingLanguages(country_code: string): boolean;
    hasHindiAsSpeakingLanguages(country_code: string): boolean;
    hasSpanishAsSpeakingLanguages(country_code: string): boolean;
    hasFrenchAsSpeakingLanguages(country_code: string): boolean;
    hasArabicAsSpeakingLanguages(country_code: string): boolean;
    hasBengaliAsSpeakingLanguages(country_code: string): boolean;
    hasRussianAsSpeakingLanguages(country_code: string): boolean;
    hasPortugueseAsSpeakingLanguages(country_code: string): boolean;
    hasIndonesianAsSpeakingLanguages(country_code: string): boolean;
    hasUrduSpeakingLanguage(country_code: string): boolean;
    hasJapaneseAsSpeakingLanguages(country_code: string): boolean;
    hasGermanAsSpeakingLanguages(country_code: string): boolean;
    hasJavaneseAsSpeakingLanguages(country_code: string): boolean;
    hasChineseAsSpeakingLanguages(country_code: string): boolean;
    hasTurkishAsSpeakingLanguages(country_code: string): boolean;
    hasKoreanAsSpeakingLanguages(country_code: string): boolean;
    hasYorubaAsSpeakingLanguages(country_code: string): boolean;
    hasFonAsSpeakingLanguages(country_code: string): boolean;
}
